// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgAi = (props: IconProps) => (
  <IconBase {...props}>
    <path
      fill="url(#ai_svg__a)"
      d="M7.5 5C5.567 5 4 7.015 4 9.5 4 7.015 2.433 5 .5 5 2.433 5 4 2.986 4 .5 4 2.986 5.567 5 7.5 5"
    />
    <path
      fill="url(#ai_svg__b)"
      d="M9.5 2.5a2 2 0 0 0-2 2 2 2 0 0 0-2-2 2 2 0 0 0 2-2 2 2 0 0 0 2 2"
    />
    <path
      fill="url(#ai_svg__c)"
      d="M9.5 7A1.5 1.5 0 0 0 8 8.5 1.5 1.5 0 0 0 6.5 7 1.5 1.5 0 0 0 8 5.5 1.5 1.5 0 0 0 9.5 7"
    />
    <defs>
      <linearGradient
        id="ai_svg__a"
        x1={0.5}
        x2={20.624}
        y1={0.5}
        y2={0.334}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#6E9FFF" stopOpacity={0} />
        <stop offset={0.164} stopColor="#6E9FFF" />
        <stop offset={0.198} stopColor="#6E9FFF" stopOpacity={0.807} />
        <stop offset={0.427} stopColor="#6E9FFF" stopOpacity={0} />
      </linearGradient>
      <linearGradient
        id="ai_svg__b"
        x1={5.5}
        x2={16.999}
        y1={0.5}
        y2={0.378}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#6E9FFF" stopOpacity={0} />
        <stop offset={0.164} stopColor="#6E9FFF" />
        <stop offset={0.198} stopColor="#6E9FFF" stopOpacity={0.807} />
        <stop offset={0.427} stopColor="#6E9FFF" stopOpacity={0} />
      </linearGradient>
      <linearGradient
        id="ai_svg__c"
        x1={6.5}
        x2={15.124}
        y1={5.5}
        y2={5.409}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#6E9FFF" stopOpacity={0} />
        <stop offset={0.164} stopColor="#6E9FFF" />
        <stop offset={0.198} stopColor="#6E9FFF" stopOpacity={0.807} />
        <stop offset={0.427} stopColor="#6E9FFF" stopOpacity={0} />
      </linearGradient>
    </defs>
  </IconBase>
);
export default SvgAi;
