// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgApplicationObservability = (props: IconProps) => (
  <IconBase {...props}>
    <path
      d="M424.19 427.44 268.02 3.84A5.87 5.87 0 0 0 262.51 0h-99.87a5.86 5.86 0 0 0-5.5 3.83L.37 427.43c-1.42 3.83 1.42 7.91 5.5 7.91H99.3c2.55 0 4.82-1.65 5.59-4.09l29.62-92.92a5.88 5.88 0 0 1 5.59-4.09h144.35c2.54 0 4.8 1.64 5.58 4.05l30.22 92.99a5.87 5.87 0 0 0 5.58 4.05h92.84c4.08 0 6.92-4.07 5.51-7.9ZM172.08 249.25c0 4.68-3.81 8.48-8.48 8.48h-13.86c-4.68 0-8.48-3.81-8.48-8.48v-93.63c0-4.68 3.81-8.49 8.48-8.49h13.86c4.68 0 8.48 3.81 8.48 8.49zm55.61 0c0 4.68-3.81 8.48-8.48 8.48h-13.86c-4.68 0-8.48-3.81-8.48-8.48V90.2c0-4.68 3.81-8.48 8.48-8.48h13.86c4.68 0 8.48 3.81 8.48 8.48zm55.61 0c0 4.68-3.81 8.48-8.49 8.48h-13.86c-4.68 0-8.49-3.81-8.49-8.48v-64.14c0-4.68 3.81-8.48 8.49-8.48h13.86c4.68 0 8.49 3.81 8.49 8.48z"
      style={{
        fill: "currentColor",
        strokeWidth: 0,
      }}
    />
  </IconBase>
);
export default SvgApplicationObservability;
