// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgArrowDown = (props: IconProps) => (
  <IconBase {...props}>
    <path d="M17.71 11.29a1 1 0 0 0-1.42 0L13 14.59V7a1 1 0 0 0-2 0v7.59l-3.29-3.3a1 1 0 0 0-1.42 1.42l5 5a1 1 0 0 0 .33.21.94.94 0 0 0 .76 0 1 1 0 0 0 .33-.21l5-5a1 1 0 0 0 0-1.42" />
  </IconBase>
);
export default SvgArrowDown;
