// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgBrowser = (props: IconProps) => (
  <IconBase {...props}>
    <path d="M19 2H9a3 3 0 0 0-3 3v1H5a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3v-1h1a3 3 0 0 0 3-3V5a3 3 0 0 0-3-3m-3 17a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-7h12Zm0-9H4V9a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1Zm4 5a1 1 0 0 1-1 1h-1V9a3 3 0 0 0-.18-1H20Zm0-9H8V5a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1Z" />
  </IconBase>
);
export default SvgBrowser;
