// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgDraggabledots = (props: IconProps) => (
  <IconBase {...props}>
    <path d="M8.5 10a2 2 0 1 0 2 2 2 2 0 0 0-2-2m0 7a2 2 0 1 0 2 2 2 2 0 0 0-2-2m7-10a2 2 0 1 0-2-2 2 2 0 0 0 2 2m-7-4a2 2 0 1 0 2 2 2 2 0 0 0-2-2m7 14a2 2 0 1 0 2 2 2 2 0 0 0-2-2m0-7a2 2 0 1 0 2 2 2 2 0 0 0-2-2" />
  </IconBase>
);
export default SvgDraggabledots;
