// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgFlip = (props: IconProps) => (
  <IconBase {...props}>
    <path d="m14.84 5.998-4.2-4.2a1.05 1.05 0 0 0-1.145-.221 1.1 1.1 0 0 0-.34.226l-4.202 4.2a1.055 1.055 0 0 0 1.492 1.492L8.85 5.08v7.671a1.05 1.05 0 0 0 2.1 0V5.08l2.4 2.41a1.054 1.054 0 1 0 1.49-1.492M13.224 22.025l-4.071-4.071a1.054 1.054 0 1 1 1.491-1.491l2.405 2.415.001.002v-7.63a1.05 1.05 0 1 1 2.1 0v7.671l2.406-2.415a1.05 1.05 0 0 1 1.49 0 1.05 1.05 0 0 1 0 1.49l-4.2 4.202a1.05 1.05 0 0 1-1.145.22 1.05 1.05 0 0 1-.471-.384z" />
  </IconBase>
);
export default SvgFlip;
