// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgFrontendObservability = (props: IconProps) => (
  <IconBase {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M4.6 3.273V1.6h11.745v3.113h-1.672v-.34a1.1 1.1 0 0 0-1.1-1.1zM4.5.4a1.1 1.1 0 0 0-1.1 1.1v1.89H1.558q-.114 0-.223.022A1.1 1.1 0 0 0 .4 4.5v4.1h.058v7.835a1.1 1.1 0 0 0 1.1 1.1h11.945a1.1 1.1 0 0 0 1.1-1.1v-1.773h1.787a1.1 1.1 0 0 0 1.1-1.1v-7.65h.055V1.5a1.1 1.1 0 0 0-1.1-1.1zM1.658 8.6v7.735h11.745V8.6zm0-1.2V4.6H13.4v2.8zM14.61 6.03v7.432h1.68V6.03zm-9.952.72h-1.44v-1.2h1.44zm1.44 0h1.44v-1.2h-1.44z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M9.071 12.344a5.3 5.3 0 0 0-.209-1.194c.388.286.67.707.778 1.194zm-.877 0a4 4 0 0 0-.24-1.14 1.3 1.3 0 0 0-.225-.39.3.3 0 0 0-.065-.054.3.3 0 0 0-.065.054 1.3 1.3 0 0 0-.225.39 4 4 0 0 0-.24 1.14zm-1.06.875h1.06a4 4 0 0 1-.24 1.14 1.3 1.3 0 0 1-.225.39.3.3 0 0 1-.065.053.3.3 0 0 1-.065-.054 1.3 1.3 0 0 1-.225-.39 4 4 0 0 1-.24-1.14m-.877-.875c.029-.436.1-.843.21-1.194-.39.286-.672.707-.779 1.194zm-.569.875h.569c.029.435.1.842.21 1.193a2.03 2.03 0 0 1-.779-1.193m-.922-.438a2.898 2.898 0 1 1 5.797 0 2.898 2.898 0 0 1-5.797 0m4.874.438c-.107.487-.39.908-.778 1.193.108-.35.18-.758.21-1.193z"
      clipRule="evenodd"
    />
  </IconBase>
);
export default SvgFrontendObservability;
