// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgGfBarAlignmentAfter = (props: IconProps) => (
  <IconBase {...props}>
    <g transform="translate(.5)">
      <circle cx={2.67} cy={2.67} r={2.67} />
      <path d="M13.42 18.08V3.42H3.06v-1.5h11.86v16.16z" />
      <path d="M1.92 18.08V2.67h1.5v15.41z" />
    </g>
  </IconBase>
);
export default SvgGfBarAlignmentAfter;
