// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgGfBarAlignmentCenter = (props: IconProps) => (
  <IconBase {...props}>
    <g transform="translate(2.5)">
      <circle cx={6.67} cy={2.67} r={2.67} />
      <path d="M11.5 18.16V3.5H0V2h13v16.16z" />
      <path d="M0 18.16V2.75h1.5v15.41z" />
    </g>
  </IconBase>
);
export default SvgGfBarAlignmentCenter;
