// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgGfInterpolationStepAfter = (props: IconProps) => (
  <IconBase {...props}>
    <circle cx={14.17} cy={2.67} r={2.67} />
    <circle cx={25.67} cy={17.33} r={2.67} />
    <circle cx={2.67} cy={17.33} r={2.67} />
    <path d="M26.42 17.33h-1.5V3.42H14.56v-1.5h11.86z" />
    <path d="M14.92 18.08H2.67v-1.5h10.75V2.67h1.5z" />
  </IconBase>
);
export default SvgGfInterpolationStepAfter;
