// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgGfInterpolationLinear = (props: IconProps) => (
  <IconBase {...props}>
    <circle cx={14.17} cy={2.67} r={2.67} />
    <circle cx={25.83} cy={17.33} r={2.67} />
    <path d="m12.278 1.835 1.156-.956 14.282 17.282-1.156.956z" />
    <circle cx={2.67} cy={17.33} r={2.67} />
    <path d="M.785 18.16 15.065.876l1.156.955L1.94 19.116z" />
  </IconBase>
);
export default SvgGfInterpolationLinear;
