// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgGfMl = (props: IconProps) => (
  <IconBase {...props}>
    <defs>
      <linearGradient
        id="gf-ml_svg__a"
        x1={67.73}
        x2={67.73}
        y1={137.67}
        y2={-0.38}
        gradientUnits="userSpaceOnUse"
      >
        <stop offset={0} stopColor="#f9ea1c" />
        <stop offset={1} stopColor="#ed5a29" />
      </linearGradient>
    </defs>
    <g data-name="Layer 2">
      <path
        d="m135.37 64.86-5.6-26.43a4.05 4.05 0 0 0-.9-1.82l-15.68-18.37a4.1 4.1 0 0 0-1-.87L83.71.57A4.2 4.2 0 0 0 81.62 0H58.54a4.2 4.2 0 0 0-1 .12L26 8a4.16 4.16 0 0 0-2 1.17L1.12 33.32A4.1 4.1 0 0 0 0 36.14v24.2a4.1 4.1 0 0 0 2.46 3.76l22.85 10L39 95.07a4.13 4.13 0 0 0 3.45 1.86h26.21l12.93 19.47a4.09 4.09 0 0 0 3.41 1.84h6a4.11 4.11 0 0 0 4.09-4.11V90.21H117a4.09 4.09 0 0 0 3.36-1.75l14.34-20.38a4.1 4.1 0 0 0 .67-3.22M86.12 34.1a3.3 3.3 0 0 0-.67.77v.05H59.83L57 30.53A3.38 3.38 0 0 0 54.24 29a3.45 3.45 0 0 0-2.86 1.45l-3.15 4.51H10.92l10.72-11.38H98.3Zm-3 4.52L72.77 55.23 62.19 38.62ZM37.75 50H8.22V38.62h37.44Zm-8.63-34.35 29.93-7.43h21.44l19.74 11.66h-75.1Zm-20.9 38h27l-8.49 12.13-18.51-8.13ZM114.87 82h-4V46.21a2.3 2.3 0 0 0-2.3-2.3h-1.39a2.3 2.3 0 0 0-2.3 2.3V82h-12V63.92a2.31 2.31 0 0 0-2.3-2.31h-1.37a2.31 2.31 0 0 0-2.3 2.31v45.64L74.48 90.84V78.36a2.3 2.3 0 0 0-2.3-2.3h-1.39a2.3 2.3 0 0 0-2.3 2.3v10.35H56.23V58.54a2.32 2.32 0 0 0-2.31-2.31h-1.38a2.32 2.32 0 0 0-2.31 2.31v30.17h-5.59l-12.39-19 21.68-31.09h.21l15.8 24.81A3.32 3.32 0 0 0 72.82 65a3.39 3.39 0 0 0 2.87-1.6L91 38.9l16.73-14.45 14.26 16.7 5 23.66Z"
        data-name="Layer 1"
        style={{
          fill: "url(#gf-ml_svg__a)",
        }}
      />
    </g>
  </IconBase>
);
export default SvgGfMl;
