// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgGfMovepaneRight = (props: IconProps) => (
  <IconBase {...props}>
    <path
      d="M21 2H3c-.549 0-1 .451-1 1v18c0 .549.451 1 1 1h18c.549 0 1-.451 1-1V3c0-.549-.451-1-1-1m-7 18H4V4h10zm6 0h-4V4h4z"
      style={{
        fillRule: "nonzero",
      }}
    />
    <path
      d="m11.3 12 3.5-3.5c.4-.4.4-1 0-1.4s-1-.4-1.4 0l-4.2 4.2c-.4.4-.4 1 0 1.4l4.2 4.2c.2.2.4.3.7.3s.5-.1.7-.3c.4-.4.4-1 0-1.4z"
      style={{
        fillRule: "nonzero",
      }}
      transform="rotate(-180 10.55 12)"
    />
  </IconBase>
);
export default SvgGfMovepaneRight;
