// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgGfPortrait = (props: IconProps) => (
  <IconBase {...props}>
    <path
      fill="inherit"
      fillRule="evenodd"
      d="M5 3.45C5 2.625 5.692 2 6.503 2c.774 0 1.503.536 1.503 1.396 0 .827-.693 1.451-1.503 1.451C5.804 4.847 5 4.327 5 3.451m1.503-.515c-.34 0-.568.25-.568.516 0 .217.23.461.568.461.34 0 .568-.25.568-.516 0-.232-.191-.461-.568-.461M4 6.298a.45.45 0 0 1 .45-.45h4.141a.45.45 0 1 1 0 .9H4.45a.45.45 0 0 1-.45-.45M4 8.098a.45.45 0 0 1 .45-.45h4.141a.45.45 0 1 1 0 .9H4.45a.45.45 0 0 1-.45-.45M10.207 9.697a.467.467 0 0 1-.027.66L8.11 12.27a.5.5 0 0 1-.122.08l-.058.03-.006.003-.088.045a.8.8 0 0 1-.348.078.95.95 0 0 1-.622-.236l-.986-.91-.034-.018-.013-.008-2.049 1.892a.467.467 0 1 1-.634-.687l2.071-1.912a.95.95 0 0 1 .622-.236c.145 0 .258.036.348.078l.088.044.006.004.058.03q.068.03.122.08l1.013.935.013-.006q.014-.009.034-.018L9.546 9.67a.467.467 0 0 1 .66.026"
      clipRule="evenodd"
    />
    <path
      fill="inherit"
      fillRule="evenodd"
      d="M11.742.938H1.258c-.116 0-.21.083-.21.187v12.75c0 .104.094.188.21.188h10.484c.116 0 .21-.084.21-.188V1.125c0-.104-.094-.187-.21-.187M1.258 0C.563 0 0 .504 0 1.125v12.75C0 14.496.563 15 1.258 15h10.484c.695 0 1.258-.504 1.258-1.125V1.125C13 .504 12.437 0 11.742 0z"
      clipRule="evenodd"
    />
  </IconBase>
);
export default SvgGfPortrait;
