// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgHomeAlt = (props: IconProps) => (
  <IconBase {...props}>
    <path d="m20 8-6-5.26a3 3 0 0 0-4 0L4 8a3 3 0 0 0-1 2.26V19a3 3 0 0 0 3 3h12a3 3 0 0 0 3-3v-8.75A3 3 0 0 0 20 8m-6 12h-4v-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1Zm5-1a1 1 0 0 1-1 1h-2v-5a3 3 0 0 0-3-3h-2a3 3 0 0 0-3 3v5H6a1 1 0 0 1-1-1v-8.75a1 1 0 0 1 .34-.75l6-5.25a1 1 0 0 1 1.32 0l6 5.25a1 1 0 0 1 .34.75Z" />
  </IconBase>
);
export default SvgHomeAlt;
