// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgMinus = (props: IconProps) => (
  <IconBase {...props}>
    <path d="M19 11H5a1 1 0 0 0 0 2h14a1 1 0 0 0 0-2" />
  </IconBase>
);
export default SvgMinus;
