// This is an auto-generated file, created by svgr-cli.
// Do not edit this file manually.
// To update the component, modify template in templates/icons.js.
// Run yarn icons:create to update.
import React from "react";
import { IconBase, IconProps } from "../IconBase";
const SvgSubject = (props: IconProps) => (
  <IconBase {...props}>
    <path d="M13 16H3a1 1 0 0 0 0 2h10a1 1 0 0 0 0-2M3 8h18a1 1 0 0 0 0-2H3a1 1 0 0 0 0 2m18 3H3a1 1 0 0 0 0 2h18a1 1 0 0 0 0-2" />
  </IconBase>
);
export default SvgSubject;
